language: node_js

nodejs:
  - lts/*
  - 8

cache: yarn

branches:
  only:
    - master

notifications:
  email:
    recipients:
      - patrick.c.connolly@gmail.com
    on_success: change
    on_failure: always
